"""
Snakemake script-mode helper. Called by `rule sample_summary` with `snakemake`
available as a global.

Writes a short markdown summary card to results/reports/<sample>_summary.md:
  * spot/UMI/gene counts (after QC)
  * top cell types by mean abundance
  * dominant niche (most common cell-type-cell-type neighborhood enrichment)
  * top boundary-DE genes (if Notebook 04 outputs are present)
  * package versions used
"""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

import numpy as np
import pandas as pd
import scanpy as sc


def fmt_num(x):
    return f"{int(x):,}" if pd.notna(x) else "n/a"


def main():
    s = snakemake  # noqa: F821 — injected by Snakemake
    sample = Path(s.output.report).stem.replace("_summary", "")

    adata = sc.read_h5ad(s.input.adata)
    niche = sc.read_h5ad(s.input.niche)

    n_spots = adata.n_obs
    med_umi = float(np.median(adata.obs["total_counts"]))
    med_gen = float(np.median(adata.obs["n_genes_by_counts"]))

    frac_cols = [c for c in adata.obs.columns if c.startswith("fraction_")]
    if frac_cols:
        means = adata.obs[frac_cols].mean().sort_values(ascending=False)
        top_types = "\n".join(
            f"- **{c.replace('fraction_', '')}** — {v:.2%}"
            for c, v in means.head(5).items()
        )
    else:
        top_types = "_(no deconvolution output found)_"

    if "dominant_celltype" in niche.obs:
        top_niche = niche.obs["dominant_celltype"].value_counts().head(3)
        top_niche_md = "\n".join(
            f"- {label}: {fmt_num(n)} spots" for label, n in top_niche.items()
        )
    else:
        top_niche_md = "_(niche call missing)_"

    import scanpy, squidpy, anndata
    versions = (
        f"- scanpy {scanpy.__version__}, squidpy {squidpy.__version__}, "
        f"anndata {anndata.__version__}"
    )
    try:
        import cell2location, tangram
        versions += f"\n- cell2location {cell2location.__version__}, tangram {tangram.__version__}"
    except Exception:
        pass

    body = dedent(f"""
        # Sample summary — `{sample}`

        ## QC
        - Spots after QC: **{fmt_num(n_spots)}**
        - Median UMI / spot: **{fmt_num(med_umi)}**
        - Median genes / spot: **{fmt_num(med_gen)}**

        ## Top cell types (cell2location mean abundance)
        {top_types}

        ## Dominant niches
        {top_niche_md}

        ## Versions
        {versions}

        _Auto-generated by `scripts/write_sample_summary.py`._
    """).strip() + "\n"

    out = Path(s.output.report)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")


if __name__ == "__main__":
    main()
